name: Deploy to github.io

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - name: Set React environment using current directory
      run: echo "::set-env name=PUBLIC_URL::/$(basename $(pwd))" 

    - name: npm install, lint
      run: |
        npm install
        npm run lint:fix
        npm run build
      env:
        REACT_APP_BASE_URL: ${{ secrets.BACKEND_URL }}
      
    - name: Deploy to github.io
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
